config:
  mcp_board_list:
    - 0x20
    - 0x21
    - 0x22
    - 0x23

  default_on:
    - [0,1]
    - [0,6]
    - [0,10]
    - [0,12]
    - [1,0]
    - [1,6]
    - [1,13]
#    - [1,15]

  bands:
    RX_Beverages:
      -
        label: NW
        address: [0,0]
      -
        label: NW + NE
        address: [0,1]
      -
        label: NE
        address: [0,2]
      -
        label: SE
        address: [0,3]
      -
        label: SW
        address: [0,4]

    160m:
      -
        label: NW
        address: [0,5]
      -
        label: NW + NE
        address: [0,6]
      -
        label: NE
        address: [0,7]
    80m:
#      -
#        label: NW
#        address: [0,8]
#      -
#        label: NW + NE
#        address: [0,9]
      -
        label: NE
        address: [0,10]
    40m:
#      -
#        label: ALL
#        address: [0,6]
      -
        label: NW
        address: [0,11]
      -
        label: NW+NE
        address: [0,12]
      -
        label: NE
        address: [0,13]
#      -
#        label: SE
#        address: [0,10]
#      -
#        label: W
#        address: [0,11]
    20m:
      -
        label: NW
        address: [0,15]
      -
        label: NW+NE
        address: [1,0]
      -
        label: NE
        address: [1,1]
      -
        label: SE
        address: [1,2]
      -
        label: NW 40'
        address: [1,3]
      -
        label: ALL
        address: [0,14]
    15m:
      -
        label: NW
        address: [1,5]
      -
        label: NW+NE
        address: [1,6]
      -
        label: NE
        address: [1,7]
      -
        label: SE
        address: [1,8]
#      -
#        label: W
#        address: [1,9]
#      -
#        label: ALL
#        address: [1,4]
    10m:
#      -
#        label: ALL
#        address: [1,10]
      -
        label: NW
        address: [1,12]
      -
        label: NW+NE
        address: [1,13]
      -
        label: NE
        address: [1,14]
      -
        label: SE
        address: [1,15]
      -
        label: NE 120'
        address: [2,0]
#    6m:
#      -
#        label: ALL
#        address: [1,14]
#      -
#        label: NW
#        address: [1,15]
#      -
#        label: NE+NW
#        address: [2,0]
#      -
#        label: NE
#        address: [2,1]
#      -
#        label: SE
#        address: [2,2]
#      -
#        label: W
#        address: [2,3]
