config:
  mcp_board_list:
    - 0x20
    - 0x21

  default_on:
    - [0,1]
    - [0,2]
    - [0,4]
    - [0,6]
    - [0,8]
    - [0,10]
    - [0,12]
    - [0,14]

  bands:
    RX:
      -
        label: BEV 1
        address: [1,1]
      -
        label: BEV 3
        address: [1,2]
    160m:
      -
        label: SLOPE VERT
        address: [0,0]
      -
        label: B
        address: [0,1]
    80m:
      -
        label: DIPOLE
        address: [0,2]
      -
        label: B
        address: [0,3]
    40m:
      -
        label: NW
        address: [0,4]
      -
        label: NE+NW
        address: [0,5]
      -
        label: NE
        address: [0,6]
    20m:
      -
        label: NW
        address: [0,7]
      -
        label: NE+NW
        address: [0,8]
      -
        label: NE
        address: [0,9]
    15m:
      -
        label: NW
        address: [0,10]
      -
        label: NE+NW
        address: [0,11]
      -
        label: NE
        address: [0,12]
    10m:
      -
        label: NW
        address: [0,13]
      -
        label: NE+NW
        address: [0,14]
      -
        label: NE
        address: [0,15]
