config:
  mcp_board_list:
    - 0x20
    - 0x21
    - 0x22
    - 0x23

  default_on:
    - [2,1]
    - [0,1]
    - [0,4]
    - [0,7]
    - [0,12]
    - [1,2]
    - [1,7]
    - [1,12]

  bands:
    RX:
      -
        label: NW BEV
        address: [2,0]
      -
        label: NW + NE BEV
        address: [2,1]
      -
        label: NE BEV
        address: [2,2]
      -
        label: SE BEV
        address: [2,3]
      -
        label: SW BEV
        address: [2,5]

    160m:
      -
        label: NW Vertical
        address: [0,0]
      -
        label: NW + NE Vertical
        address: [0,1]
      -
        label: NW Vertical
        address: [0,2]
    80m:
      -
        label: NW Sloper
        address: [0,3]
      -
        label: NW + NE Sloper
        address: [0,4]
      -
        label: NE Sloper
        address: [0,5]
    40m:
      -
        label: NW
        address: [0,6]
      -
        label: NE+NW
        address: [0,7]
      -
        label: NE
        address: [0,8]
      -
        label: SE
        address: [0,9]
      -
        label: W
        address: [0,10]
    20m:
      -
        label: NW
        address: [0,11]
      -
        label: NE+NW
        address: [0,12]
      -
        label: NE
        address: [0,13]
      -
        label: SE
        address: [0,14]
      -
        label: W
        address: [0,15]
    15m:
      -
        label: NW
        address: [1,1]
      -
        label: NE+NW

        address: [1,2]
      -
        label: NE
        address: [1,3]
      -
        label: SE
        address: [1,4]
      -
        label: W
        address: [1,5]
    10m:
      -
        label: NW
        address: [1,6]
      -
        label: NE+NW
        address: [1,7]
      -
        label: NE
        address: [1,8]
      -
        label: SE
        address: [1,9]
      -
        label: W
        address: [1,10]
     6m:
      -
        label: NW
        address: [1,11]
      -
        label: NE+NW
        address: [1,12]
      -
        label: NE
        address: [1,13]
      -
        label: SE
        address: [1,14]
      -
        label: W
        address: [1,15]
